# Generated by Django 4.1.1 on 2022-09-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDoro_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
